[cluster-admin] Highlighted list items for better UX
cloudoperators/greenhouse pull request #120
Opened 2024-04-09 14:21 UTC by TilmanHaupt

To ensure a similar user experience (UX), the following features are proposed:

- Minimum width column for the ResourceStatus
- Rows are now grey if the user hovers
- Rows are light grey if the detail view for the cluster is open
- If the user clicks the active list item the detail panel is closed.

2024-04-09 14:25 UTC, edda approved these changes
🙏

2024-04-10 10:00 UTC, uwe-mayer requested changes

2024-04-10 10:00 UTC, uwe-mayer commented on ui/cluster-admin/src/store.ts
> +  showClusterDetails: string | undefined
I would prefer to keep a boolean here for easier handling and reference.

2024-04-10 10:00 UTC, uwe-mayer commented on ui/cluster-admin/src/components/ClusterListItem.tsx
> +        showClusterDetails === props?.cluster?.metadata?.name ? "active" : ""
The `clusterDetails.cluster` should already provide the necessary data. No need to use `showClusterDetails` here.

2024-04-10 10:00 UTC, uwe-mayer commented on ui/cluster-admin/src/components/ClusterDetail.tsx
> +    setShowClusterDetails(undefined)
We need to also `null` the `cluster` prop in `clusterDetails` here to make sure the `active` state works correctly

2024-04-10 10:03 UTC, uwe-mayer commented on ui/cluster-admin/src/components/ClusterDetail.tsx
> +    setShowClusterDetails(undefined)
So we need `setClusterDetails` from `useStore()` and set it here

2024-04-10 10:14 UTC, uwe-mayer commented
Thanks for adding this! Just some remarks on how to extract `active` state without changing the `showClusterDetails` type

2024-04-10 18:51 UTC, TilmanHaupt commented
> Thanks for adding this! Just some remarks on how to extract `active` state without changing the `showClusterDetails` type

Should be all fine now. :)

2024-04-12 07:03 UTC, uwe-mayer commented on ui/cluster-admin/src/components/ClusterListItem.tsx
> +          props?.cluster?.metadata?.name && showClusterDetails
Nice, no need to `null` the `clusterDetails.cluster`

2024-04-12 07:03 UTC, uwe-mayer approved these changes

2024-04-12 08:23 UTC, merged