Feat(ui): Add secrets admin
cloudoperators/greenhouse pull request #214
Opened 2024-05-17 12:57 UTC by uwe-mayer

Spin up your local setup as described in the [README](https://github.com/cloudoperators/greenhouse/compare/feat/ui/secret-admin-view?expand=1#diff-9bd83305b4bec8da6217246d88ae426dccecd08dc7412a078e106d61b7dd8fc0) to give this admin view a spin...

2024-05-17 12:58 UTC, uwe-mayer commented
@ArtieReus @TilmanHaupt 
If you could have a look, since this is the refactoring extracting secrets from https://github.com/cloudoperators/greenhouse/pull/142

2024-05-21 12:36 UTC, ArtieReus requested changes

2024-05-21 12:36 UTC, ArtieReus commented on ui/secret-admin/package.json
> +      "description": "Set to true if app is to be embedded in another existing app or page, like e.g. Elektra.  If set to true the app won't render a page header/footer and instead render only the co
We probably need to remove the example from Elektra. It is not related in this context.

2024-05-22 12:45 UTC, uwe-mayer commented on ui/secret-admin/package.json
> +    "juno-ui-components": "https://assets.juno.global.cloud.sap/libs/juno-ui-components@2.13.5/package.tgz",
:heavy_check_mark:

2024-05-22 12:45 UTC, uwe-mayer commented on ui/secret-admin/package.json
> +    "juno-ui-components": "*",
removed from the peer dependencies altogether

2024-05-22 12:45 UTC, uwe-mayer commented on ui/secret-admin/package.json
> +    "url-state-provider": "*",
removed from the peer dependencies altogether

2024-05-22 12:46 UTC, uwe-mayer commented on ui/secret-admin/src/App.js
> +  useCommunication()
removed from App.js

2024-05-22 14:48 UTC, ArtieReus approved these changes
lgtm

2024-05-22 15:08 UTC, merged