Plugin-Admin
cloudoperators/greenhouse pull request #36
Opened 2024-03-25 16:01 UTC by TilmanHaupt

Plugin which shows selected data from the pluginConfig, and aims to allow to edit some of this data in the future.

2024-03-25 17:24 UTC, edda requested changes
Some small things :)

2024-03-25 17:24 UTC, edda commented on ui/plugin-admin/src/components/Plugin.js
> +        <p>{plugin.name}</p>
wrapping the cell's content in a `<p>` tag is not necessary. The only reason you would want to wrap a cell's content in a wrapper element is if you have multiple children within the cell and you don't want the default vertical flexbox layout applied to it. See documentation for the `cellVerticalAlignment` prop of the `DataGrid` component.

2024-03-25 17:24 UTC, edda commented on ui/plugin-admin/src/components/Plugin.js
> +        {plugin.clusterName ? <p>{plugin.clusterName}</p> : <p>&mdash;</p>}
same as above with the wrapping `<p>`

2024-03-25 17:24 UTC, edda commented on ui/plugin-admin/src/components/Plugin.js
> +          <p>&mdash;</p>
unnecessary `<p>` wrapper

2024-03-25 17:24 UTC, edda commented on ui/plugin-admin/src/components/Plugin.js
> +        <p>
`<p>` wrapper :)

2024-03-25 17:24 UTC, edda commented on ui/plugin-admin/src/components/PluginDetail.js
> +                          {url.name}{" "}
Not a fan of the `{" "}`. If you want to create margin to potential siblings, please use css. E.g.
```jsx
<a
  href=...
  ...
  className="mr-3"
>
```

2024-03-25 17:24 UTC, edda commented on ui/plugin-admin/src/components/PluginDetail.js
> +                    })}{" "}
As above, please no spacing via `{" "}`

2024-03-26 14:42 UTC, edda approved these changes
+1

2024-03-26 15:02 UTC, IvoGoman approved these changes

2024-03-27 10:21 UTC, merged