Feat/plugin preset cluster overrides
cloudoperators/greenhouse pull request #515
Opened 2024-09-02 09:51 UTC by gciezkowski-acc

## Description
I added the field clusterOptionOverrides to Plugin Preset Spec struct.

## What type of PR is this? (check all applicable)

- [X] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

- Related Issue # (issue)
- Closes #491 
- Fixes # (issue)

> Remove if not applicable

## Added tests?

- [X] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help
- [ ] Separate ticket for tests # (issue/pr)

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Added to documentation?

- [ ] 📜 README.md
- [X] 🤝 Documentation pages updated
- [ ] 🙅 no documentation needed
- [ ] (if applicable) generated OpenAPI docs for CRD changes

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

2024-09-02 10:05 UTC, IvoGoman commented on pkg/controllers/plugin/pluginpreset_controller_test.go
> +		Entry("with defined pluginPresetOverrides but for another cluster",
```suggestion
		Entry("with defined pluginPresetOverrides for the correct cluster",
```

2024-09-02 10:05 UTC, IvoGoman commented on pkg/controllers/plugin/pluginpreset_controller_test.go
> +		Entry("with defined pluginPresetOverrides but for another cluster",
```suggestion
		Entry("with defined pluginPresetOverrides for the cluster",
```

2024-09-02 12:22 UTC, gciezkowski-acc commented on pkg/controllers/plugin/pluginpreset_controller.go
> +			return true
Done

2024-09-02 12:23 UTC, gciezkowski-acc commented on pkg/controllers/plugin/pluginpreset_controller_test.go
> +		Entry("with defined pluginPresetOverrides but for another cluster",
Done

2024-09-02 12:23 UTC, gciezkowski-acc commented on pkg/controllers/plugin/pluginpreset_controller_test.go
> +		Entry("with defined pluginPresetOverrides but for another cluster",
Done

2024-09-03 10:00 UTC, IvoGoman requested changes
Could you run `make generate` to update also the generated CRDs?

2024-09-03 10:00 UTC, IvoGoman commented on pkg/apis/greenhouse/v1alpha1/pluginpreset_types.go
> +type ClusterOptionOverride struct {
This field should be optional
```suggestion
// +kubebuilder:validation:Optional
type ClusterOptionOverride struct {
```

2024-09-03 10:01 UTC, IvoGoman commented on pkg/admission/pluginpreset_webhook_test.go
> +				ClusterOptionOverrides: []greenhousev1alpha1.ClusterOptionOverride{},
This won't be necessary after making the field optional. The overrides should not be required

2024-09-03 11:26 UTC, gciezkowski-acc commented on pkg/apis/greenhouse/v1alpha1/pluginpreset_types.go
> +type ClusterOptionOverride struct {
Done

2024-09-03 14:01 UTC, IvoGoman commented
> Could you run `make generate` to update also the generated CRDs?

This still needs to be done ^^

2024-09-05 14:11 UTC, IvoGoman approved these changes
Thanks, looks good.

2024-09-05 14:28 UTC, merged