fix(rbac): allow org members to view TeamRole & TeamRoleBindings
cloudoperators/greenhouse pull request #647
Opened 2024-10-17 06:51 UTC by IvoGoman

## Description

Organization members should be able to view TeamRoles and TeamRoleBindings. 

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

- Related Issue # (issue)
- Closes # (issue)
- Fixes # (issue)

> Remove if not applicable

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help
- [ ] Separate ticket for tests # (issue/pr)

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Added to documentation?

- [ ] 📜 README.md
- [ ] 🤝 Documentation pages updated
- [ ] 🙅 no documentation needed
- [ ] (if applicable) generated OpenAPI docs for CRD changes

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-10-17 07:24 UTC, uwe-mayer approved these changes

2024-10-17 07:50 UTC, uwe-mayer requested changes
We still need to update org-admin permissions to include TeamRoleBindings..
Blocking this for a moment

2024-10-17 08:16 UTC, IvoGoman commented
> We still need to update org-admin permissions to include TeamRoleBindings.. Blocking this for a moment

Since Cluster Admins should be able to manage access on the remote cluster, the access to the TeamRole was moved from the Org Admin to the Cluster Admin.
By default the Org Admin includes all access from the other profiles.

2024-10-17 09:26 UTC, uwe-mayer commented on pkg/rbac/role.go
> +			Resources: []string{"clusters", "plugins", "pluginpresets", "teams", "teammemberships", "teamroles", "teamrolebindings"},
```suggestion
			Resources: []string{"*"},
```

2024-10-17 09:26 UTC, uwe-mayer commented on pkg/rbac/role.go
> +			Resources: []string{"teamroles"},
Should org-admins not be able to manipulate all Greenhouse resources? So we could lose lines 17-21 of this file?
```suggestion
			Resources: []string{"*"},
```

2024-10-17 09:26 UTC, uwe-mayer commented on pkg/rbac/role.go
> +			Resources: []string{"teamroles"},
Ah no. We have to distinguish `organizations` only in orgs namespace...
But still we can consolidate with lines 17-21 and add clusters + plugins
And we should add the List/watch/get of PluginDefinitions to the org-admin as well, right?

2024-10-17 09:26 UTC, uwe-mayer commented on pkg/rbac/role.go
> +			Resources: []string{"clusters", "plugins", "pluginpresets", "teams", "teammemberships", "teamroles", "teamrolebindings"},
Same here for the `organization`, disregard.

2024-10-17 09:26 UTC, uwe-mayer commented on pkg/rbac/role.go
> +			Resources: []string{"teamroles"},
```suggestion
			Resources: []string{"clusters", "plugins", "pluginpresets", "teams", "teammemberships", "teamroles", "teamrolebindings"},
```

2024-10-22 13:23 UTC, uwe-mayer approved these changes

2024-10-23 09:14 UTC, merged