chore(docs): Improve cluster onboarding documentation
cloudoperators/greenhouse pull request #655
Opened 2024-10-23 09:05 UTC by uwe-mayer

## Description
This aims to better define and outline the permission scopes needed to onboard a `Cluster` to Greenhouse

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

- Closes #539

2024-10-23 09:46 UTC, kengou requested changes
I'm updating the `greenhousectl cluster onboard ...` just now. Please bear with me there will be just a slight change. Once finished I'm going to update your docs here

2024-10-25 13:15 UTC, IvoGoman commented on docs/user-guides/cluster/onboarding.md
> +Onboarding a `Cluster` to Greenhouse will require you to authenticate to two different kubernetes clusters via repsective `kubeconfig` files:
```suggestion
Onboarding a `Cluster` to Greenhouse will require you to authenticate to two different Kubernetes clusters via respective `kubeconfig` files:
```

2024-10-25 13:15 UTC, IvoGoman commented on docs/user-guides/cluster/onboarding.md
> +- `greenhouse`: The cluster your Greenhouse installation is running on. You need `organization-admin` or `cluster-admin` priviledges.
```suggestion
- `greenhouse`: The cluster your Greenhouse installation is running on. You need `organization-admin` or `cluster-admin` privileges.
```

2024-10-25 13:15 UTC, IvoGoman commented on docs/user-guides/cluster/onboarding.md
> +- `bootstrap`: The cluster you want to onboard. You need `system:masters` priviledges.
```suggestion
- `bootstrap`: The cluster you want to onboard. You need `system:masters` privileges.
```

2024-10-25 13:15 UTC, IvoGoman commented on docs/user-guides/cluster/onboarding.md
> +_Organization_ > _Clusters_ > _Access greenhouse cluster_.
```suggestion
_Organization_ > _Clusters_ > _Access Greenhouse cluster_.
```

2024-10-25 13:15 UTC, IvoGoman commented on docs/user-guides/cluster/onboarding.md
> +For accessing the `greenhouse` cluster, the `greenhousectl` will expect your default kubernetes [`kubeconfig` file](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfi
```suggestion
For accessing the `greenhouse` cluster, the `greenhousectl` will expect your default Kubernetes [`kubeconfig` file](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/) and [`context`](https://kubernetes.io/docs/reference/kubectl/generated/kubectl_config/kubectl_config_use-context/) to be set to `greenhouse`.
```

2024-10-29 09:15 UTC, kengou commented on docs/user-guides/cluster/onboarding.md
> +greenhousectl cluster bootstrap --kubeconfig=<path/to/greenhouse-kubeconfig-file> --bootstrap-kubeconfig <path/to/bootstrap-kubeconfig-file> --org <greenhouse-organization-name> --cluster-name <name>
```suggestion
greenhousectl cluster bootstrap --kubeconfig=<path/to/bootstrap-kubeconfig-file> --greenhouse-kubeconfig <path/to/greenhouse-kubeconfig-file> --org <greenhouse-organization-name> --cluster-name <name>
```

2024-10-29 09:16 UTC, kengou commented on docs/user-guides/cluster/onboarding.md
> +The location of the `kubeconfig` file to the `bootstrap` cluster is passed via the `--bootstrap-kubeconfig` flag.
```suggestion
The location of the `kubeconfig` file to the `bootstrap` cluster is passed via the `--kubeconfig` flag or via the `KUBECONFIG` enviorment variable
```

2024-10-29 09:22 UTC, kengou commented on docs/user-guides/cluster/onboarding.md
> +For accessing the `greenhouse` cluster, the `greenhousectl` will expect your default kubernetes [`kubeconfig` file](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfi
```suggestion
For accessing the `greenhouse` cluster, the `greenhousectl` will expect you to pass [`kubeconfig` file](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/) downloaded from Greenhouse dashboard via `--greenhouse-kubeconfig` flag
```

2024-10-29 09:22 UTC, kengou commented on docs/user-guides/cluster/onboarding.md
> +The easiest way for doing so is passing the `--kubeconfig` (and optionally `--kubecontext`) flag to your `greenhousectl` command.
```suggestion

```

2024-11-05 09:27 UTC, uwe-mayer commented on docs/user-guides/cluster/onboarding.md
> +For accessing the `greenhouse` cluster, the `greenhousectl` will expect your default Kubernetes [`kubeconfig` file](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfi
```suggestion
For accessing the `greenhouse` cluster, the `greenhousectl` will expect your default Kubernetes [`kubeconfig` file](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/) and [`context`](https://kubernetes.io/docs/reference/kubectl/generated/kubectl_config/kubectl_config_use-context/) to be set to `bootstrap`.
```

2024-11-05 12:46 UTC, IvoGoman approved these changes

2024-11-06 11:02 UTC, kengou approved these changes

2024-11-06 12:06 UTC, merged