fix(service-proxy): Well defined urls for exposed services with max 63
cloudoperators/greenhouse pull request #678
Opened 2024-10-28 14:12 UTC by uwe-mayer

## Description
This enforces:

- no `--` in `Cluster` names
- max length of 40 chars for `Cluster` names, so we make sure the `hash` of `service-name+namespace` fits into the exposed service subdomain.

Exposed service URLs will look like:
```
https://$cluster--$hash.$organisation.$basedomain, where $hash = service--$namespace
```
This reduces all host decomposition to only use the extracted `ClusterName` from the incoming request. We made sure this is welldefined and unambigous.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

- Related Issue #78
- Closes # #661 

> Remove if not applicable

## Changed tests?

- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help
- [ ] Separate ticket for tests # (issue/pr)

2024-10-29 08:29 UTC, IvoGoman requested changes

2024-10-29 08:54 UTC, richardtief commented
Could you please update the docs along the changes made: https://github.com/cloudoperators/greenhouse/blob/main/docs/user-guides/plugin/plugin-deployment.md#urls-for-exposed-services

2024-11-01 12:27 UTC, uwe-mayer commented on pkg/admission/utils.go
> +		l.Error(err, "found object name with double dashes, admission will be denied")
We decided to log anyhow as this depends on verbosity of the controller. 
Todo: Unify across webhooks.

2024-11-01 12:27 UTC, uwe-mayer commented on cmd/service-proxy/instrumentation.go
> -				ctx = context.WithValue(ctx, ctxNameKey{}, name)
Fixed

2024-11-01 12:28 UTC, uwe-mayer commented on pkg/admission/utils.go
> +		return admission.Warnings{fmt.Sprintf("you cannot create an object with a name longer than %d", length)}, err
We are only erroring now

2024-11-01 12:28 UTC, uwe-mayer commented
> Could you please update the docs along the changes made: https://github.com/cloudoperators/greenhouse/blob/main/docs/user-guides/plugin/plugin-deployment.md#urls-for-exposed-services

Updated the docs

2024-11-04 14:44 UTC, IvoGoman commented on cmd/service-proxy/instrumentation.go
> +	next := pm.ReverseProxy()
Since this variable is only used within the call to `return injector(..)`. Could we call `pm.ReverseProxy()` directly?

2024-11-06 12:18 UTC, IvoGoman approved these changes

2024-11-07 10:29 UTC, merged