docs(architecture): update observability architecture
cloudoperators/greenhouse pull request #732
Opened 2024-11-12 15:20 UTC by richardtief

2024-11-12 15:57 UTC, ibakshay commented on docs/architecture/monitoring-architecture.png
Question: Do Plugin and PluginDefinition have n-1 relation?

2024-11-12 15:57 UTC, ibakshay commented on docs/architecture/monitoring-architecture.png
Suggestion: Shall we name this box? Is it a namespace? If yes, PluginDefinition needs to be outside? As it is a cluster-wide resource? 🤔
![image](https://github.com/user-attachments/assets/f9da0ac8-d766-4eb2-9786-219da602b46d)

2024-11-12 15:57 UTC, ibakshay commented on docs/architecture/monitoring.md
> +Observability in software and infrastructure has become essential for operation the complexity of modern Clouds. The concept centers on understanding the internal states of systems based on the data
```suggestion
Observability in software and infrastructure has become essential for operating the complex modern cloud environments. The concept centers on understanding the internal states of systems based on the data they produce, enabling teams to:
```

2024-11-13 08:38 UTC, richardtief commented on docs/architecture/monitoring-architecture.png
Look at the arrow. 🙂 _One Plugin has only one PluginDefinition_ 

But I guess other people will also not understand this so I switched the arrow and make it n-1. 👍🏻

2024-11-13 08:54 UTC, richardtief commented on docs/architecture/monitoring-architecture.png
True! Will update the drawing

2024-11-13 12:17 UTC, ibakshay approved these changes
LGTM! 🔥

2024-11-13 13:20 UTC, viennaa requested changes
Some small refinements for the lower section. Nice drawing, way better than the old one :)

2024-11-13 13:30 UTC, viennaa approved these changes
<3

2024-11-13 13:31 UTC, merged