feat(controllers) Deprecation of propagation controller (#777)
cloudoperators/greenhouse pull request #788
Opened 2024-11-28 14:47 UTC by gciezkowski-acc

## Description

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help
- [ ] Separate ticket for tests # (issue/pr)

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Added to documentation?

- [ ] 📜 README.md
- [ ] 🤝 Documentation pages updated
- [ ] 🙅 no documentation needed
- [ ] (if applicable) generated OpenAPI docs for CRD changes

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

2024-12-02 11:21 UTC, IvoGoman requested changes
The logic for removing the resources from the remote system and the finalizer on successful deletion is missing.

2024-12-02 13:53 UTC, gciezkowski-acc commented
> The logic for removing the resources from the remote system and the finalizer on successful deletion is missing

The logic of removing resources from remote is here. I didn't touch it.
/https://github.com/cloudoperators/greenhouse/pull/788/files#diff-ad100e6e1bfb9a5e365411f8a9ba2f40784c2f224474b80754b0199aab201df9R125-R138:~:text=%7D-,//%20cleanup,%7D,-remoteObjectResource%2C%20err

Removing finalizer when it is success is here:
https://github.com/cloudoperators/greenhouse/pull/788/files#diff-ad100e6e1bfb9a5e365411f8a9ba2f40784c2f224474b80754b0199aab201df9L106-L110:~:text=%7D-,if%20removeFinalizer%20%7B,%7D,-return%20ctrl.

I left the existing logic as it was.

2024-12-05 08:23 UTC, IvoGoman commented
> > The logic for removing the resources from the remote system and the finalizer on successful deletion is missing
> 
> The logic of removing resources from remote is here. I didn't touch it. /https://github.com/cloudoperators/greenhouse/pull/788/files#diff-ad100e6e1bfb9a5e365411f8a9ba2f40784c2f224474b80754b0199aab201df9R125-R138:~:text=%7D-,//%20cleanup,%7D,-remoteObjectResource%2C%20err
> 
> Removing finalizer when it is success is here: https://github.com/cloudoperators/greenhouse/pull/788/files#diff-ad100e6e1bfb9a5e365411f8a9ba2f40784c2f224474b80754b0199aab201df9L106-L110:~:text=%7D-,if%20removeFinalizer%20%7B,%7D,-return%20ctrl.
> 
> I left the existing logic as it was.

That logic only kicks in if the resource (team, cluster etc.) in the central cluster is deleted. This PR should remove all propagated resources from the remote cluster. 

This would require to run the deletion logic to remove the resources from the remote cluster and remove the finalizer if all of the resoruces were removed from the remote cluster.

2025-01-08 17:59 UTC, IvoGoman reviewed
Looks good from my end. @uwe-mayer could you, as original author, take a look that we have not missed anything. The CRDs should be unused and could be removed as well. This would clean up all the CRs. The not found errors are covered by the change. I believe there is no usage currently.

2025-01-17 07:40 UTC, uwe-mayer requested changes
this looks good. Let's just remove the `Requeue`.
CRDs then need to be cleaned by hand.

2025-01-17 07:40 UTC, uwe-mayer commented on pkg/controllers/propagation_reconciler.go
>  	return ctrl.Result{RequeueAfter: DefaultRequeueInterval}, nil
No need to `RequeueAfter` here...

2025-01-17 12:49 UTC, gciezkowski-acc commented on pkg/controllers/propagation_reconciler.go
>  	return ctrl.Result{RequeueAfter: DefaultRequeueInterval}, nil
Done

2025-01-24 14:40 UTC, uwe-mayer approved these changes

2025-01-27 17:54 UTC, IvoGoman approved these changes

2025-01-28 09:25 UTC, merged